# Generated by Django 2.1.2 on 2019-03-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('canteen_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=256)),
                ('position', models.CharField(default=None, max_length=256)),
                ('capacity', models.CharField(default=None, max_length=256)),
                ('business_hours', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=256)),
                ('rate', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('detail', models.CharField(default=None, max_length=1024)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('window_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=256)),
                ('location', models.CharField(default=None, max_length=256)),
                ('canteen_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.Canteen')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='window_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.Window'),
        ),
    ]
