# Generated by Django 2.1.2 on 2019-03-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
