# Generated by Django 2.1.2 on 2019-03-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0002_auto_20190321_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=256)),
                ('name', models.CharField(default='Black', max_length=256)),
            ],
        ),
    ]
