# Generated by Django 2.1.2 on 2019-03-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatarUrl',
            field=models.CharField(default='https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1553269747858&di=bf518acca5f758415bc173ecbe7fbea8&imgtype=0&src=http%3A%2F%2Fpic.51yuansu.com%2Fpic3%2Fcover%2F01%2F69%2F80%2F595f67c3a6eb1_610.jpg', max_length=1024),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
