# Generated by Django 2.1.2 on 2019-03-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0004_auto_20190322_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
