# Generated by Django 2.1.2 on 2019-03-25 12:54

from django.db import migrations, models
import django.db.models.deletion
import hangwei.models


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0005_user_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(default=None, max_length=256)),
                ('star', models.IntegerField(default=0)),
                ('consent', models.IntegerField(default=0)),
                ('opposition', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='img',
            field=models.ImageField(blank=True, default=None, upload_to=hangwei.models.rename_file),
        ),
        migrations.AddField(
            model_name='comment',
            name='dish_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.Dish'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='hangwei.User'),
        ),
    ]
