# Generated by Django 2.1.2 on 2019-03-27 15:43

from django.db import migrations, models
import django.db.models.deletion
import hangwei.models


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0006_auto_20190325_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureInComment',
            fields=[
                ('picture_in_comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, default=None, upload_to=hangwei.models.rename_file)),
                ('comment_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='hangwei.Comment')),
            ],
        ),
    ]
