# Generated by Django 2.1.2 on 2019-03-30 09:00

from django.db import migrations, models
import django.db.models.deletion
import hangwei.models


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0007_pictureincomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('comment_reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(default=None, max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.Comment')),
                ('commenter_user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_user', to='hangwei.User')),
                ('mentioned_user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mentioned_user', to='hangwei.User')),
            ],
        ),
        migrations.AlterField(
            model_name='pictureincomment',
            name='img',
            field=models.ImageField(blank=True, default=None, upload_to=hangwei.models.rename_comment_file),
        ),
    ]
