# Generated by Django 2.1.2 on 2019-04-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0008_auto_20190330_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('comment_like_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.Comment')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='hangwei.User')),
            ],
        ),
    ]
