# Generated by Django 2.1.2 on 2019-04-05 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0009_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureincomment',
            name='comment_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hangwei.Comment'),
        ),
    ]
