# Generated by Django 2.1.2 on 2019-04-10 04:24

from django.db import migrations, models
import hangwei.models


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0010_auto_20190405_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='img',
            field=models.ImageField(blank=True, default=None, upload_to=hangwei.models.rename_window_file),
        ),
    ]
