# Generated by Django 2.1.2 on 2019-04-13 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0012_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply_old',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_old',
        ),
        migrations.AddField(
            model_name='message',
            name='user_mentioned',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_mentioned', to='hangwei.User'),
        ),
    ]
