# Generated by Django 2.1.2 on 2019-04-16 07:03

from django.db import migrations, models
import django.db.models.deletion
import hangwei.models


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0013_auto_20190413_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCache',
            fields=[
                ('dishCache_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=256)),
                ('rate', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('detail', models.CharField(default=None, max_length=1024)),
                ('img', models.ImageField(blank=True, default=None, upload_to=hangwei.models.rename_file)),
                ('window_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.Window')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('detail',)},
        ),
    ]
