# Generated by Django 2.1.2 on 2019-04-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0014_auto_20190416_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcache',
            name='detail',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
