# Generated by Django 2.1.2 on 2019-04-16 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0015_auto_20190416_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenCache',
            fields=[
                ('canteen_cache_id', models.AutoField(primary_key=True, serialize=False)),
                ('canteen_id', models.IntegerField(default=-1)),
                ('name', models.CharField(default=None, max_length=256)),
                ('position', models.CharField(default=None, max_length=256)),
                ('capacity', models.CharField(default=None, max_length=256)),
                ('business_hours', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(default=None, max_length=512)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='hangwei.User')),
            ],
        ),
        migrations.CreateModel(
            name='HaveEaten',
            fields=[
                ('have_eaten_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.Dish')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.User')),
            ],
        ),
        migrations.CreateModel(
            name='WantEat',
            fields=[
                ('want_eat_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.Dish')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.User')),
            ],
        ),
        migrations.CreateModel(
            name='WindowCache',
            fields=[
                ('window_cache_id', models.AutoField(primary_key=True, serialize=False)),
                ('window_id', models.IntegerField(default=-1)),
                ('name', models.CharField(default=None, max_length=256)),
                ('location', models.CharField(default=None, max_length=256)),
                ('canteen', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.Canteen')),
            ],
        ),
        migrations.RenameField(
            model_name='dishcache',
            old_name='dishCache_id',
            new_name='dish_cache_id',
        ),
        migrations.RenameField(
            model_name='dishcache',
            old_name='window_id',
            new_name='window',
        ),
        migrations.RemoveField(
            model_name='dishcache',
            name='rate',
        ),
        migrations.AddField(
            model_name='dishcache',
            name='dish_id',
            field=models.IntegerField(default=-1),
        ),
    ]
