# Generated by Django 2.1.2 on 2019-04-22 04:24

from django.db import migrations, models
import django.utils.timezone
import hangwei.models


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0016_auto_20190416_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='haveeaten',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wanteat',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dishcache',
            name='img',
            field=models.ImageField(blank=True, default=None, upload_to=hangwei.models.rename_cachefile),
        ),
    ]
