# Generated by Django 2.1.2 on 2019-04-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0017_auto_20190422_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
