# Generated by Django 2.1.7 on 2019-04-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0018_message_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheckin',
            fields=[
                ('user_checkin_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.User')),
            ],
        ),
    ]
