# Generated by Django 2.1.7 on 2019-05-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0019_usercheckin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default=None, max_length=128)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
    ]
