# Generated by Django 2.1.7 on 2019-05-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0020_hotsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(default=0)),
                ('people_num', models.IntegerField(default=0)),
                ('canteen', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.Canteen')),
            ],
        ),
    ]
