# Generated by Django 2.2.1 on 2019-05-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0025_feedback_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishTagCache',
            fields=[
                ('dish_tag_cache_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(default=None, max_length=256)),
                ('dish', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='DishTag',
            fields=[
                ('dish_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(default=None, max_length=256)),
                ('dish', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hangwei.Dish')),
            ],
        ),
    ]
