# Generated by Django 2.2.1 on 2019-05-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangwei', '0026_dishtag_dishtagcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='detail',
            field=models.TextField(default=None),
        ),
    ]
